version: '3'
services:
  db:
    image: postgres:latest
    container_name: "db"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '9000:9000'
  server:
    build: ./server
    container_name: "server"
    ports:
      - '8000:8000'
    depends_on:
      - db
  front:
    build: ./front
    container_name: front
    ports:
      - '3000:3000'
    volumes:
      - ./front/app/:/usr/src/app
    command: /bin/sh -c 'npm install && npm run dev'